version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 12
    commands:
      - echo Installing libraries
      - npm install
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Success
artifacts:
  files:
    - '**/*'